# Generated by Django 6.0.4 on 2026-05-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockbatch',
            constraint=models.UniqueConstraint(fields=('item', 'lot_number'), name='uniq_item_lot'),
        ),
    ]
