# Generated by Django 6.0.4 on 2026-05-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='issue_type',
            field=models.CharField(choices=[('GENERAL', 'General Feedback'), ('DAMAGED', 'Damaged Item'), ('EXPIRED', 'Expired / Spoiled Item'), ('WRONG_QUANTITY', 'Wrong Quantity'), ('WRONG_ITEM', 'Wrong Item Received')], default='GENERAL', max_length=20),
        ),
    ]
