# Generated by Django 6.0.4 on 2026-05-03 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('farmers', '0004_backfill_linked_user'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interventionapplication',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='interventionapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'FULFILLED'])), fields=('farmer', 'program'), name='uniq_active_application'),
        ),
    ]
