# Generated by Django 6.0.4 on 2026-05-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_partial_unique_active_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionapplication',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled')], db_index=True, default='SUBMITTED', max_length=20),
        ),
    ]
