# Generated by Django 6.0.4 on 2026-04-30 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('civil_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated'), ('COMMON_LAW', 'Common-law')], max_length=20)),
                ('highest_education', models.CharField(choices=[('NONE', 'No formal education'), ('ELEMENTARY', 'Elementary'), ('HIGH_SCHOOL', 'High School'), ('VOCATIONAL', 'Vocational / Technical'), ('COLLEGE', 'College'), ('POST_GRAD', 'Post-graduate')], default='ELEMENTARY', max_length=20)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('is_4ps', models.BooleanField(default=False, verbose_name='4Ps beneficiary')),
                ('is_pwd', models.BooleanField(default=False, verbose_name='PWD')),
                ('is_ip', models.BooleanField(default=False, verbose_name='Indigenous People')),
                ('rsbsa_reference', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('barangay', models.CharField(choices=[('Baccuit Norte', 'Baccuit Norte'), ('Baccuit Sur', 'Baccuit Sur'), ('Bagbag', 'Bagbag'), ('Ballay', 'Ballay'), ('Bella Union', 'Bella Union'), ('Bili', 'Bili'), ('Bungro', 'Bungro'), ('Cabaroan (Poro)', 'Cabaroan (Poro)'), ('Calumbaya', 'Calumbaya'), ('Carmay', 'Carmay'), ('Casilagan', 'Casilagan'), ('Central East (Poblacion)', 'Central East (Poblacion)'), ('Central West (Poblacion)', 'Central West (Poblacion)'), ('Dili', 'Dili'), ('Disso-or', 'Disso-or'), ('Guerrero', 'Guerrero'), ('Lasip', 'Lasip'), ('Lingsat', 'Lingsat'), ('Mabanbanag', 'Mabanbanag'), ('Maoasoas', 'Maoasoas'), ('Pagdalagan Norte', 'Pagdalagan Norte'), ('Pagdalagan Sur', 'Pagdalagan Sur'), ('Palina East', 'Palina East'), ('Palina West', 'Palina West'), ('Penroad (Sao-it)', 'Penroad (Sao-it)'), ('Piayong', 'Piayong'), ('Picinan', 'Picinan'), ('Pindangan East', 'Pindangan East'), ('Pindangan West', 'Pindangan West'), ('Quintarong', 'Quintarong'), ('Rabon', 'Rabon'), ('Ramot', 'Ramot'), ('San Agustin (Pugo)', 'San Agustin (Pugo)'), ('San Felipe', 'San Felipe'), ('San Isidro (Baraoas)', 'San Isidro (Baraoas)'), ('San Juan', 'San Juan'), ('San Luis', 'San Luis'), ('Santa Monica', 'Santa Monica'), ('Sapilang', 'Sapilang')], max_length=100)),
                ('sitio', models.CharField(blank=True, max_length=100)),
                ('livelihood_type', models.CharField(choices=[('RICE', 'Rice Farming'), ('CORN', 'Corn Farming'), ('VEGETABLE', 'Vegetable Farming'), ('FRUIT', 'Fruit Farming'), ('LIVESTOCK', 'Livestock'), ('POULTRY', 'Poultry'), ('FISHERY', 'Fishery'), ('OTHER', 'Other')], default='RICE', max_length=20)),
                ('farm_area_ha', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('household_size', models.PositiveSmallIntegerField(default=1)),
                ('consent_dpa', models.BooleanField(default=False)),
                ('consent_dpa_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('encoded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoded_farmers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='FarmParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_ha', models.DecimalField(decimal_places=4, max_digits=8)),
                ('commodity', models.CharField(max_length=100)),
                ('land_type', models.CharField(choices=[('IRRIGATED', 'Irrigated'), ('RAINFED_UPLAND', 'Rainfed Upland'), ('RAINFED_LOWLAND', 'Rainfed Lowland')], max_length=20)),
                ('ownership_type', models.CharField(choices=[('OWNED', 'Owned'), ('TENANT', 'Tenant'), ('LESSEE', 'Lessee'), ('CARETAKER', 'Caretaker')], max_length=20)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='farmers.farmer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
