# Generated by Django 6.0.4 on 2026-05-03 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_newest_first_ordering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='linked_user',
            field=models.OneToOneField(blank=True, help_text="The CLIENT account that can log in and view this farmer's data.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
