# Generated by Django 6.0.4 on 2026-05-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_backfill_linked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='barangay',
            field=models.CharField(choices=[('Baccuit Norte', 'Baccuit Norte'), ('Baccuit Sur', 'Baccuit Sur'), ('Bagbag', 'Bagbag'), ('Ballay', 'Ballay'), ('Bella Union', 'Bella Union'), ('Bili', 'Bili'), ('Bungro', 'Bungro'), ('Cabaroan (Poro)', 'Cabaroan (Poro)'), ('Calumbaya', 'Calumbaya'), ('Carmay', 'Carmay'), ('Casilagan', 'Casilagan'), ('Central East (Poblacion)', 'Central East (Poblacion)'), ('Central West (Poblacion)', 'Central West (Poblacion)'), ('Dili', 'Dili'), ('Disso-or', 'Disso-or'), ('Guerrero', 'Guerrero'), ('Lasip', 'Lasip'), ('Lingsat', 'Lingsat'), ('Mabanbanag', 'Mabanbanag'), ('Maoasoas', 'Maoasoas'), ('Pagdalagan Norte', 'Pagdalagan Norte'), ('Pagdalagan Sur', 'Pagdalagan Sur'), ('Palina East', 'Palina East'), ('Palina West', 'Palina West'), ('Penroad (Sao-it)', 'Penroad (Sao-it)'), ('Piayong', 'Piayong'), ('Picinan', 'Picinan'), ('Pindangan East', 'Pindangan East'), ('Pindangan West', 'Pindangan West'), ('Quintarong', 'Quintarong'), ('Rabon', 'Rabon'), ('Ramot', 'Ramot'), ('San Agustin (Pugo)', 'San Agustin (Pugo)'), ('San Felipe', 'San Felipe'), ('San Isidro (Baraoas)', 'San Isidro (Baraoas)'), ('San Juan', 'San Juan'), ('San Luis', 'San Luis'), ('Santa Monica', 'Santa Monica'), ('Sapilang', 'Sapilang')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
