# Generated by Django 6.0.4 on 2026-05-11 12:15

import apps.farmers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_add_db_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.farmers.models.farmer_photo_path, verbose_name='Profile photo'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='verification_document',
            field=models.FileField(blank=True, help_text='Image or PDF proving 4Ps / PWD / IP status.', null=True, upload_to=apps.farmers.models.farmer_verification_path, verbose_name='Verification document'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='UNVERIFIED', max_length=12),
        ),
    ]
