# Generated by Django 6.0.4 on 2026-05-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sync_is_staff_with_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('CLIENT', 'Client')], db_index=True, default='CLIENT', max_length=10),
        ),
    ]
