# Generated by Django 6.0.4 on 2026-05-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='scheduled_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DELIVERED', 'Delivered'), ('DELAYED', 'Delayed'), ('RESCHEDULED', 'Rescheduled'), ('OUT_OF_STOCK', 'Out of Stock'), ('UNAVAILABLE', 'Unavailable')], db_index=True, default='SCHEDULED', max_length=20),
        ),
    ]
