# Generated by Django 6.0.4 on 2026-04-30 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('source_agency', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_barangays', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('livelihood_type', 'Livelihood Type'), ('is_4ps', '4Ps Beneficiary'), ('is_pwd', 'PWD'), ('is_ip', 'Indigenous People'), ('farm_area_ha', 'Farm Area (ha)'), ('household_size', 'Household Size')], max_length=30)),
                ('operator', models.CharField(choices=[('eq', 'equals'), ('gte', 'greater than or equal'), ('lte', 'less than or equal'), ('is_true', 'is true')], max_length=10)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('fail_message', models.CharField(blank=True, max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='programs.program')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_beneficiary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_per_farmer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_items', to='inventory.inventoryitem')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='programs.program')),
            ],
            options={
                'unique_together': {('program', 'inventory_item')},
            },
        ),
    ]
