BAUANG_BARANGAYS = [
    "Baccuit Norte",
    "Baccuit Sur",
    "Bagbag",
    "Ballay",
    "Bella Union",
    "Bili",
    "Bungro",
    "Cabaroan (Poro)",
    "Calumbaya",
    "Carmay",
    "Casilagan",
    "Central East (Poblacion)",
    "Central West (Poblacion)",
    "Dili",
    "Disso-or",
    "Guerrero",
    "Lasip",
    "Lingsat",
    "Mabanbanag",
    "Maoasoas",
    "Pagdalagan Norte",
    "Pagdalagan Sur",
    "Palina East",
    "Palina West",
    "Penroad (Sao-it)",
    "Piayong",
    "Picinan",
    "Pindangan East",
    "Pindangan West",
    "Quintarong",
    "Rabon",
    "Ramot",
    "San Agustin (Pugo)",
    "San Felipe",
    "San Isidro (Baraoas)",
    "San Juan",
    "San Luis",
    "Santa Monica",
    "Sapilang",
]

BARANGAY_CHOICES = [(b, b) for b in BAUANG_BARANGAYS]
